# Automatically generated by configure - do not modify

all:
SRC_PATH=/data/vms/sandbox/aix432/build/qemu
TARGET_DIRS=ppc-softmmu
GDB=/usr/bin/gdb
SUBDIRS=
PYTHON=/data/vms/sandbox/aix432/build/qemu/build-s3/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/data/vms/sandbox/aix432/build/qemu/build-s3/pyvenv/bin/python3 -B /data/vms/sandbox/aix432/build/qemu/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=/usr/bin/genisoimage
MESON=/data/vms/sandbox/aix432/build/qemu/build-s3/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_WITH_COMPILERS=
